name: Deploy bootstrap-icons website.
on:
  push:
    branches:
      - master
jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'

      - run: npm install
      - run: npm run font
      - run: npm run copy:svg 
      - run: npm run copy
      - run: npm run build
      - run: rm -rf fonts/react
      - run: cp lib/*.js ./
      - run: cp lib/*.d.ts ./
      - run: mkdir icon
      - run: cp icons/icons/*svg ./icon
      - run: rm -rf index.js
      - run: ls -al

      - name: Generate Contributors Images
        uses: jaywcjlove/github-action-contributors@main
        with:
          filter-author: (renovate\[bot\]|renovate-bot|dependabot\[bot\])
          output: fonts/CONTRIBUTORS.svg
          avatarSize: 42

      - name: Create Tag
        id: create_tag
        uses: jaywcjlove/create-tag-action@main
        with:
          package-path: ./package.json

      - name: get tag version
        id: tag_version
        uses: jaywcjlove/changelog-generator@main

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          commit_message: ${{steps.tag_version.outputs.tag}} ${{ github.event.head_commit.message }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./fonts

      - name: Generate Changelog
        id: changelog
        uses: jaywcjlove/changelog-generator@main
        with:
          head-ref: ${{steps.create_tag.outputs.version}}
          filter-author: (jaywcjlove|小弟调调™|dependabot\[bot\]|Renovate Bot)
          filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

      - name: Create Release
        uses: ncipollo/release-action@v1
        if: steps.create_tag.outputs.successful
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ steps.create_tag.outputs.version }}
          tag: ${{ steps.create_tag.outputs.version }}
          body: |
            [![](https://img.shields.io/badge/Open%20in-unpkg-blue)](https://uiwjs.github.io/npm-unpkg/#/pkg/@uiw/bootstrap-icons@${{steps.create_tag.outputs.versionNumber}}/file/README.md) [![npm bundle size](https://img.shields.io/bundlephobia/minzip/@uiw/bootstrap-icons)](https://bundlephobia.com/result?p=@uiw/bootstrap-icons@${{steps.create_tag.outputs.versionNumber}})
            
            Documentation ${{ steps.changelog.outputs.tag }}: https://raw.githack.com/uiwjs/bootstrap-icons/${{ steps.changelog.outputs.gh-pages-short-hash }}/index.html  
            Comparing Changes: ${{ steps.changelog.outputs.compareurl }} 
            
            ```bash
            npm i @uiw/bootstrap-icons@${{steps.create_tag.outputs.versionNumber}}
            ```
            
            ${{ steps.changelog.outputs.changelog }}

      - run: rm -rf fonts/*.html
      - run: npm publish --access public
        name: 📦  @uiw/bootstrap-icons publish to NPM
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

        